# Hariku V2 — accessible calendar & automation for screen-reader users.
# Copyright (C) 2024-2026 InfiArtt (Rafli) and Hariku contributors.
#
# This file is part of Hariku, released under the GNU General Public License,
# version 3 or (at your option) any later version, with the Hariku Extension
# Exception. See LICENSE and LICENSE-EXCEPTION. Distributed WITHOUT ANY WARRANTY.
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Country names for the ISO 3166-1 codes wheretheiss.at gives for the point
below the ISS, in English and Indonesian. Written for Hariku; codes that are
not here are simply not named.
"""

# code: (English, Indonesian)
COUNTRIES = {
    "AD": ("Andorra", "Andorra"),
    "AE": ("the United Arab Emirates", "Uni Emirat Arab"),
    "AF": ("Afghanistan", "Afganistan"),
    "AG": ("Antigua and Barbuda", "Antigua dan Barbuda"),
    "AI": ("Anguilla", "Anguilla"),
    "AL": ("Albania", "Albania"),
    "AM": ("Armenia", "Armenia"),
    "AO": ("Angola", "Angola"),
    "AQ": ("Antarctica", "Antarktika"),
    "AR": ("Argentina", "Argentina"),
    "AS": ("American Samoa", "Samoa Amerika"),
    "AT": ("Austria", "Austria"),
    "AU": ("Australia", "Australia"),
    "AW": ("Aruba", "Aruba"),
    "AZ": ("Azerbaijan", "Azerbaijan"),
    "BA": ("Bosnia and Herzegovina", "Bosnia dan Herzegovina"),
    "BB": ("Barbados", "Barbados"),
    "BD": ("Bangladesh", "Bangladesh"),
    "BE": ("Belgium", "Belgia"),
    "BF": ("Burkina Faso", "Burkina Faso"),
    "BG": ("Bulgaria", "Bulgaria"),
    "BH": ("Bahrain", "Bahrain"),
    "BI": ("Burundi", "Burundi"),
    "BJ": ("Benin", "Benin"),
    "BL": ("Saint Barthélemy", "Saint Barthélemy"),
    "BM": ("Bermuda", "Bermuda"),
    "BN": ("Brunei", "Brunei Darussalam"),
    "BO": ("Bolivia", "Bolivia"),
    "BR": ("Brazil", "Brasil"),
    "BS": ("the Bahamas", "Bahama"),
    "BT": ("Bhutan", "Bhutan"),
    "BW": ("Botswana", "Botswana"),
    "BY": ("Belarus", "Belarus"),
    "BZ": ("Belize", "Belize"),
    "CA": ("Canada", "Kanada"),
    "CC": ("the Cocos (Keeling) Islands", "Kepulauan Cocos (Keeling)"),
    "CD": ("the Democratic Republic of the Congo", "Republik Demokratik Kongo"),
    "CF": ("the Central African Republic", "Republik Afrika Tengah"),
    "CG": ("the Republic of the Congo", "Republik Kongo"),
    "CH": ("Switzerland", "Swiss"),
    "CI": ("Côte d'Ivoire", "Pantai Gading"),
    "CK": ("the Cook Islands", "Kepulauan Cook"),
    "CL": ("Chile", "Chili"),
    "CM": ("Cameroon", "Kamerun"),
    "CN": ("China", "Tiongkok"),
    "CO": ("Colombia", "Kolombia"),
    "CR": ("Costa Rica", "Kosta Rika"),
    "CU": ("Cuba", "Kuba"),
    "CV": ("Cape Verde", "Tanjung Verde"),
    "CW": ("Curaçao", "Curaçao"),
    "CX": ("Christmas Island", "Pulau Christmas"),
    "CY": ("Cyprus", "Siprus"),
    "CZ": ("Czechia", "Ceko"),
    "DE": ("Germany", "Jerman"),
    "DJ": ("Djibouti", "Djibouti"),
    "DK": ("Denmark", "Denmark"),
    "DM": ("Dominica", "Dominika"),
    "DO": ("the Dominican Republic", "Republik Dominika"),
    "DZ": ("Algeria", "Aljazair"),
    "EC": ("Ecuador", "Ekuador"),
    "EE": ("Estonia", "Estonia"),
    "EG": ("Egypt", "Mesir"),
    "EH": ("Western Sahara", "Sahara Barat"),
    "ER": ("Eritrea", "Eritrea"),
    "ES": ("Spain", "Spanyol"),
    "ET": ("Ethiopia", "Etiopia"),
    "FI": ("Finland", "Finlandia"),
    "FJ": ("Fiji", "Fiji"),
    "FK": ("the Falkland Islands", "Kepulauan Falkland"),
    "FM": ("Micronesia", "Mikronesia"),
    "FO": ("the Faroe Islands", "Kepulauan Faroe"),
    "FR": ("France", "Prancis"),
    "GA": ("Gabon", "Gabon"),
    "GB": ("the United Kingdom", "Britania Raya"),
    "GD": ("Grenada", "Grenada"),
    "GE": ("Georgia", "Georgia"),
    "GF": ("French Guiana", "Guyana Prancis"),
    "GH": ("Ghana", "Ghana"),
    "GI": ("Gibraltar", "Gibraltar"),
    "GL": ("Greenland", "Greenland"),
    "GM": ("the Gambia", "Gambia"),
    "GN": ("Guinea", "Guinea"),
    "GP": ("Guadeloupe", "Guadeloupe"),
    "GQ": ("Equatorial Guinea", "Guinea Khatulistiwa"),
    "GR": ("Greece", "Yunani"),
    "GT": ("Guatemala", "Guatemala"),
    "GU": ("Guam", "Guam"),
    "GW": ("Guinea-Bissau", "Guinea-Bissau"),
    "GY": ("Guyana", "Guyana"),
    "HK": ("Hong Kong", "Hong Kong"),
    "HN": ("Honduras", "Honduras"),
    "HR": ("Croatia", "Kroasia"),
    "HT": ("Haiti", "Haiti"),
    "HU": ("Hungary", "Hongaria"),
    "ID": ("Indonesia", "Indonesia"),
    "IE": ("Ireland", "Irlandia"),
    "IL": ("Israel", "Israel"),
    "IN": ("India", "India"),
    "IO": ("the British Indian Ocean Territory", "Wilayah Samudra Hindia Britania"),
    "IQ": ("Iraq", "Irak"),
    "IR": ("Iran", "Iran"),
    "IS": ("Iceland", "Islandia"),
    "IT": ("Italy", "Italia"),
    "JM": ("Jamaica", "Jamaika"),
    "JO": ("Jordan", "Yordania"),
    "JP": ("Japan", "Jepang"),
    "KE": ("Kenya", "Kenya"),
    "KG": ("Kyrgyzstan", "Kirgizstan"),
    "KH": ("Cambodia", "Kamboja"),
    "KI": ("Kiribati", "Kiribati"),
    "KM": ("the Comoros", "Komoro"),
    "KN": ("Saint Kitts and Nevis", "Saint Kitts dan Nevis"),
    "KP": ("North Korea", "Korea Utara"),
    "KR": ("South Korea", "Korea Selatan"),
    "KW": ("Kuwait", "Kuwait"),
    "KY": ("the Cayman Islands", "Kepulauan Cayman"),
    "KZ": ("Kazakhstan", "Kazakhstan"),
    "LA": ("Laos", "Laos"),
    "LB": ("Lebanon", "Lebanon"),
    "LC": ("Saint Lucia", "Saint Lucia"),
    "LI": ("Liechtenstein", "Liechtenstein"),
    "LK": ("Sri Lanka", "Sri Lanka"),
    "LR": ("Liberia", "Liberia"),
    "LS": ("Lesotho", "Lesotho"),
    "LT": ("Lithuania", "Lituania"),
    "LU": ("Luxembourg", "Luksemburg"),
    "LV": ("Latvia", "Latvia"),
    "LY": ("Libya", "Libya"),
    "MA": ("Morocco", "Maroko"),
    "MC": ("Monaco", "Monako"),
    "MD": ("Moldova", "Moldova"),
    "ME": ("Montenegro", "Montenegro"),
    "MF": ("Saint Martin", "Saint Martin"),
    "MG": ("Madagascar", "Madagaskar"),
    "MH": ("the Marshall Islands", "Kepulauan Marshall"),
    "MK": ("North Macedonia", "Makedonia Utara"),
    "ML": ("Mali", "Mali"),
    "MM": ("Myanmar", "Myanmar"),
    "MN": ("Mongolia", "Mongolia"),
    "MO": ("Macau", "Makau"),
    "MP": ("the Northern Mariana Islands", "Kepulauan Mariana Utara"),
    "MQ": ("Martinique", "Martinik"),
    "MR": ("Mauritania", "Mauritania"),
    "MS": ("Montserrat", "Montserrat"),
    "MT": ("Malta", "Malta"),
    "MU": ("Mauritius", "Mauritius"),
    "MV": ("the Maldives", "Maladewa"),
    "MW": ("Malawi", "Malawi"),
    "MX": ("Mexico", "Meksiko"),
    "MY": ("Malaysia", "Malaysia"),
    "MZ": ("Mozambique", "Mozambik"),
    "NA": ("Namibia", "Namibia"),
    "NC": ("New Caledonia", "Kaledonia Baru"),
    "NE": ("Niger", "Niger"),
    "NF": ("Norfolk Island", "Pulau Norfolk"),
    "NG": ("Nigeria", "Nigeria"),
    "NI": ("Nicaragua", "Nikaragua"),
    "NL": ("the Netherlands", "Belanda"),
    "NO": ("Norway", "Norwegia"),
    "NP": ("Nepal", "Nepal"),
    "NR": ("Nauru", "Nauru"),
    "NU": ("Niue", "Niue"),
    "NZ": ("New Zealand", "Selandia Baru"),
    "OM": ("Oman", "Oman"),
    "PA": ("Panama", "Panama"),
    "PE": ("Peru", "Peru"),
    "PF": ("French Polynesia", "Polinesia Prancis"),
    "PG": ("Papua New Guinea", "Papua Nugini"),
    "PH": ("the Philippines", "Filipina"),
    "PK": ("Pakistan", "Pakistan"),
    "PL": ("Poland", "Polandia"),
    "PM": ("Saint Pierre and Miquelon", "Saint Pierre dan Miquelon"),
    "PN": ("the Pitcairn Islands", "Kepulauan Pitcairn"),
    "PR": ("Puerto Rico", "Puerto Riko"),
    "PS": ("Palestine", "Palestina"),
    "PT": ("Portugal", "Portugal"),
    "PW": ("Palau", "Palau"),
    "PY": ("Paraguay", "Paraguay"),
    "QA": ("Qatar", "Qatar"),
    "RE": ("Réunion", "Réunion"),
    "RO": ("Romania", "Rumania"),
    "RS": ("Serbia", "Serbia"),
    "RU": ("Russia", "Rusia"),
    "RW": ("Rwanda", "Rwanda"),
    "SA": ("Saudi Arabia", "Arab Saudi"),
    "SB": ("the Solomon Islands", "Kepulauan Solomon"),
    "SC": ("Seychelles", "Seychelles"),
    "SD": ("Sudan", "Sudan"),
    "SE": ("Sweden", "Swedia"),
    "SG": ("Singapore", "Singapura"),
    "SH": ("Saint Helena", "Saint Helena"),
    "SI": ("Slovenia", "Slovenia"),
    "SK": ("Slovakia", "Slowakia"),
    "SL": ("Sierra Leone", "Sierra Leone"),
    "SM": ("San Marino", "San Marino"),
    "SN": ("Senegal", "Senegal"),
    "SO": ("Somalia", "Somalia"),
    "SR": ("Suriname", "Suriname"),
    "SS": ("South Sudan", "Sudan Selatan"),
    "ST": ("São Tomé and Príncipe", "Sao Tome dan Principe"),
    "SV": ("El Salvador", "El Salvador"),
    "SX": ("Sint Maarten", "Sint Maarten"),
    "SY": ("Syria", "Suriah"),
    "SZ": ("Eswatini", "Eswatini"),
    "TC": ("the Turks and Caicos Islands", "Kepulauan Turks dan Caicos"),
    "TD": ("Chad", "Chad"),
    "TF": ("the French Southern Territories", "Wilayah Selatan Prancis"),
    "TG": ("Togo", "Togo"),
    "TH": ("Thailand", "Thailand"),
    "TJ": ("Tajikistan", "Tajikistan"),
    "TK": ("Tokelau", "Tokelau"),
    "TL": ("Timor-Leste", "Timor Leste"),
    "TM": ("Turkmenistan", "Turkmenistan"),
    "TN": ("Tunisia", "Tunisia"),
    "TO": ("Tonga", "Tonga"),
    "TR": ("Türkiye", "Turki"),
    "TT": ("Trinidad and Tobago", "Trinidad dan Tobago"),
    "TV": ("Tuvalu", "Tuvalu"),
    "TW": ("Taiwan", "Taiwan"),
    "TZ": ("Tanzania", "Tanzania"),
    "UA": ("Ukraine", "Ukraina"),
    "UG": ("Uganda", "Uganda"),
    "UM": ("the United States Minor Outlying Islands", "Kepulauan Terluar Kecil Amerika Serikat"),
    "US": ("the United States", "Amerika Serikat"),
    "UY": ("Uruguay", "Uruguay"),
    "UZ": ("Uzbekistan", "Uzbekistan"),
    "VA": ("Vatican City", "Vatikan"),
    "VC": ("Saint Vincent and the Grenadines", "Saint Vincent dan Grenadine"),
    "VE": ("Venezuela", "Venezuela"),
    "VG": ("the British Virgin Islands", "Kepulauan Virgin Britania Raya"),
    "VI": ("the United States Virgin Islands", "Kepulauan Virgin Amerika Serikat"),
    "VN": ("Vietnam", "Vietnam"),
    "VU": ("Vanuatu", "Vanuatu"),
    "WF": ("Wallis and Futuna", "Wallis dan Futuna"),
    "WS": ("Samoa", "Samoa"),
    "XK": ("Kosovo", "Kosovo"),
    "YE": ("Yemen", "Yaman"),
    "YT": ("Mayotte", "Mayotte"),
    "ZA": ("South Africa", "Afrika Selatan"),
    "ZM": ("Zambia", "Zambia"),
    "ZW": ("Zimbabwe", "Zimbabwe"),
}


def country_name(code, language="en"):
    """The country's name in `language` ("en" or "id"), or None if unknown."""
    names = COUNTRIES.get(str(code or "").upper())
    if not names:
        return None
    return names[1] if language == "id" else names[0]
